/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio22;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String nomeProduto;
        float precoCusto;
        float precoVenda;
        float totalCusto = 0.0f;
        float totalVenda = 0.0f;
        int qtdProdutos = 4;

        Scanner leitor = new Scanner(System.in);

        for (int i = 0; i < qtdProdutos; i++) {
            System.out.print("Digite o nome do produto: ");
            nomeProduto = leitor.next();

            System.out.print("Digite o preço de custo do produto: ");
            precoCusto = leitor.nextFloat();

            System.out.print("Digite o preço de venda do produto: ");
            precoVenda = leitor.nextFloat();

            totalCusto += precoCusto;
            totalVenda += precoVenda;

            if (precoCusto < precoVenda) {
                System.out.println("Lucro");
            } else if (precoCusto > precoVenda) {
                System.out.println("Prejuíso");
            } else {
                System.out.println("Empate");
            }

            System.out.println(nomeProduto + ", Preço de custo: " + precoCusto + ", Peço de venda: " + precoVenda);
        }

        System.out.println("A média do preço de custo é: " + (totalCusto / qtdProdutos));
        System.out.println("A média do preço de venda é: " + (totalVenda / qtdProdutos));

    }
}
