/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaCondicionalSe;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int media = 7;

        if (media >= 7) {
            if (media == 10){
                //PARABENS, APROVADO COM NOTA MÁXIMA
            } else {
                //PARABENS
            }
        } else {
            //REPROVADO
        }
    }
}
