/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VariaveisTiposOperacoes;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Tipos de dados
        
        int idade = 24;
        float cotacaoDolar = 5.0f;
        double cotacaoEuro = 6.0d;
        char genero = 'M';
        byte ponto = 0;
        boolean estaCadastrado = false;
        String nome = "João Vitor Martins Araújo";
        
        
        /*
        Operadores Aritiméticos
        
            + -> Soma
            - -> Subtração
            / -> Divisão
            * -> Multiplicação
            % -> Resto da divisão
        
        */
    }
}
